apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cnrm-manager-controllerresource.yaml
  - cnrm-manager-resourcestatsrecorder.yaml
  - cnrm-workload-identity.yaml
  - configconnector.yaml
